# Generated by Django 5.1.4 on 2025-05-20 08:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_story_chat_story'),
        ('users', '0003_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='grammar_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='reading_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='topics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='message',
            name='vocabulary_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ChatAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_messages', models.IntegerField(default=0)),
                ('total_words', models.IntegerField(default=0)),
                ('unique_words', models.IntegerField(default=0)),
                ('average_vocabulary_score', models.FloatField(default=0)),
                ('average_grammar_score', models.FloatField(default=0)),
                ('average_sentiment_score', models.FloatField(default=0)),
                ('total_duration', models.FloatField(default=0)),
                ('topics_covered', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('vocabulary_growth', models.JSONField(default=dict)),
                ('grammar_improvement', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='chat.chat')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('metrics', models.JSONField(default=dict)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='users.child')),
            ],
            options={
                'ordering': ['-achieved_at'],
            },
        ),
        migrations.CreateModel(
            name='CharacterInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=100)),
                ('total_time_spent', models.FloatField(default=0)),
                ('total_chats', models.IntegerField(default=0)),
                ('favorite_topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_interactions', to='users.child')),
            ],
            options={
                'ordering': ['-last_interaction'],
                'unique_together': {('child', 'character')},
            },
        ),
    ]
