# Generated by Django 5.1.4 on 2025-05-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='age_group',
            field=models.CharField(choices=[('3-5', '3-5 years'), ('6-8', '6-8 years'), ('9-12', '9-12 years')], default='5-8', max_length=20),
        ),
        migrations.AddField(
            model_name='child',
            name='favorite_topics',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='child',
            name='interests',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='child',
            name='languages',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='child',
            name='learning_goals',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='child',
            name='reading_level',
            field=models.CharField(default='Beginner', max_length=50),
        ),
    ]
